const API_URL = '/api/consignment';
const IMAGE_API_URL = '/api/consignment-image';
const EXPIRY_API_URL = '/api/consignment-expiry';
async function request(method='GET',body){const response=await fetch(API_URL,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Shopify request failed (${response.status})`);return payload}
async function expiryRequest(body){const response=await fetch(EXPIRY_API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Expiry metadata update failed (${response.status})`);return payload}
export async function getConsignmentData(){const[data,expiryResponse]=await Promise.all([request(),fetch(EXPIRY_API_URL)]);const expiry=await expiryResponse.json().catch(()=>({values:{}}));const values=expiryResponse.ok?(expiry.values||{}):{};return{...data,items:(data.items||[]).map(item=>({...item,...(values[item.id]||{})}))}}
export async function searchShopifyCategories(search){const response=await fetch(`${API_URL}?taxonomy=${encodeURIComponent(search.trim())}`);const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Could not search Shopify categories (${response.status})`);return payload.categories||[]}
export function createConsignor(consignor){return request('POST',{operation:'createConsignor',consignor})} export function updateConsignor(consignorId,consignor){return request('PATCH',{operation:'updateConsignor',consignorId,consignor})} export function deleteConsignor(consignorId){return request('DELETE',{operation:'deleteConsignor',consignorId})}
function dataUrlToImageBlob(dataUrl){const match=/^data:(image\/[a-z0-9.+-]+);base64,(.+)$/i.exec(dataUrl||'');if(!match)throw new Error('The selected photo could not be prepared. Please take the photo again.');const mimeType=match[1].toLowerCase(),binary=atob(match[2]),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i+=1)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type:mimeType})}
async function uploadImage(dataUrl,alt){if(!dataUrl?.startsWith('data:image/'))return null;const imageBlob=dataUrlToImageBlob(dataUrl),formData=new FormData(),extension=imageBlob.type==='image/png'?'png':'jpg';formData.append('image',imageBlob,`consignment-${Date.now()}.${extension}`);formData.append('alt',alt||'Consignment item');const response=await fetch(IMAGE_API_URL,{method:'POST',body:formData}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Image upload failed (${response.status})`);return payload}
async function prepareItemPhoto(item){const uploaded=await uploadImage(item.photo,item.description);if(!uploaded)return item;return{...item,photoId:uploaded.id,photo:uploaded.url||item.photo}}
export async function createConsignmentItems(consignorId,items){const manualItems=items.map(item=>({category:item.category,type:'',description:item.description,size:item.size,condition:item.condition,price:item.price,brand:item.brand,notes:item.notes}));const saved=await request('POST',{operation:'createItems',consignorId,items:manualItems});await Promise.all(saved.map((item,index)=>expiryRequest({itemId:item.id,receivedDate:items[index]?.receivedDate||'',consignmentTerm:items[index]?.consignmentTerm||'',expiryDate:items[index]?.expiryDate||''})));return saved}
export async function updateConsignmentItem(itemId,item){const saved=await request('PATCH',{operation:'updateItem',itemId,item:{category:item.category,type:'',description:item.description,size:item.size,condition:item.condition,price:item.price,brand:item.brand,notes:item.notes}});await expiryRequest({itemId,receivedDate:item.receivedDate||'',consignmentTerm:item.consignmentTerm||'',expiryDate:item.expiryDate||''});return saved}
export function deleteConsignmentItem(itemId){return request('DELETE',{operation:'deleteItem',itemId})} export async function syncShopifyProduct(itemId,product){const preparedProduct=await prepareItemPhoto(product);return request('POST',{operation:'syncProduct',itemId,product:preparedProduct})} export function updateConsignmentItemStatus(itemId,status,details={}){return request('POST',{operation:'updateItemStatus',itemId,status,...details})} export function recordConsignorPayout(payout){return request('POST',{operation:'recordPayout',...payout})} export function importConsignmentData(kind,rows){return request('POST',{operation:'importData',kind,rows})}
