import {Plus,Users,PackageSearch,ReceiptText,WalletCards} from 'lucide-react';

const money=(n)=>`$${Number(n||0).toFixed(2)}`;
function expiryMeta(item){if(!item.expiryDate)return null;const today=new Date();today.setHours(0,0,0,0);const expiry=new Date(`${item.expiryDate}T12:00:00`);if(Number.isNaN(expiry.getTime()))return null;expiry.setHours(0,0,0,0);const days=Math.ceil((expiry-today)/86400000);return{days,status:days<0?'Expired':'Active'}}
export default function DashboardPage({consignors,items,onNavigate,onNewItem,onNewConsignor}){
 const sold=items.filter(i=>i.status==='Sold'||i.dateSold);const available=items.filter(i=>['Available','Active','Draft'].includes(i.status)&&!i.paidOut);const unpaid=sold.filter(i=>!i.paidOut);const sales=sold.reduce((s,i)=>s+Number(i.salePrice??i.price??0),0);const owed=unpaid.reduce((sum,item)=>sum+(Number(item.salePrice??item.price??0)*Number(item.commissionPct||0))/100,0);
 const tracked=available.map(item=>({item,meta:expiryMeta(item)})).filter(x=>x.meta);const expiring7=tracked.filter(x=>x.meta.days>=0&&x.meta.days<=7).length;const expiring30=tracked.filter(x=>x.meta.days>=0&&x.meta.days<=30).length;const expired=tracked.filter(x=>x.meta.status==='Expired').length;const recent=[...items].slice(-5).reverse();
 return <div className="jci-page"><div className="jci-pagehead"><div><p className="jci-eyebrow">Overview</p><h1>Dashboard</h1><p className="jci-sub">Track consignors, inventory, sales and payouts.</p></div><div className="jci-actions"><button className="jci-btn" onClick={onNewConsignor}><Plus size={17}/>Add consignor</button><button className="jci-btn secondary" onClick={onNewItem}><Plus size={17}/>Add item</button></div></div>
 <div className="jci-grid"><button className="jci-card jci-metric" onClick={()=>onNavigate('consignors')}><Users size={20}/><span>Consignors</span><strong>{consignors.length}</strong><small className="jci-small">View details →</small></button><button className="jci-card jci-metric" onClick={()=>onNavigate('items')}><PackageSearch size={20}/><span>Available items</span><strong>{available.length}</strong><small className="jci-small">View details →</small></button><button className="jci-card jci-metric" onClick={()=>onNavigate('sales')}><ReceiptText size={20}/><span>Sales total</span><strong>{money(sales)}</strong><small className="jci-small">View details →</small></button><button className="jci-card jci-metric" onClick={()=>onNavigate('payouts')}><WalletCards size={20}/><span>Owed to consignors</span><strong>{money(owed)}</strong><small className="jci-small">View details →</small></button></div>
 <section className="jci-card" style={{marginTop:18}}><h2>Consignment Expiry</h2><p className="jci-sub">Optional term tracking. Expired items stay in inventory until you choose an action.</p><div className="jci-grid jci-expiry-grid" style={{marginTop:14}}><button className="jci-card jci-metric" onClick={()=>onNavigate('items')}><span>Expiring in 7 days</span><strong>{expiring7}</strong><small className="jci-small">View items →</small></button><button className="jci-card jci-metric" onClick={()=>onNavigate('items')}><span>Expiring in 30 days</span><strong>{expiring30}</strong><small className="jci-small">View items →</small></button><button className="jci-card jci-metric" onClick={()=>onNavigate('items')}><span>Expired</span><strong>{expired}</strong><small className="jci-small">Action required →</small></button></div></section>
 <div className="jci-dashboard-bottom" style={{marginTop:18}}><section className="jci-card"><h2 style={{marginBottom:12}}>Recent items</h2>{recent.length?recent.map(i=><button type="button" className="jci-recent-row" key={i.id} onClick={()=>onNavigate(i.status==='Sold'?'sales':'items')}><span><strong>{i.description||i.shopifyTitle||i.itemNumber}</strong><small className="jci-small">{i.itemNumber?`#${i.itemNumber} · `:''}{i.status}</small></span><b>{money(i.status==='Sold'?(i.salePrice??i.price):i.price)}</b></button>):<p className="jci-sub">No items yet.</p>}</section><section className="jci-card"><h2>Getting started</h2><p className="jci-sub">Add consignors and inventory here. Transactions, reports, Import / Export and Settings are available directly from the navigation above.</p></section></div></div>;
}
